blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import logging




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blogapp/', include('blogapp.urls',namespace='blogapp')),
    url(r'^api/posts', include('blogapp.api.urls', namespace='blogapp-api')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$',auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social'))


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogapp/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	PostListAPIView
	)
urlpatterns = [
url(r'^$', PostListAPIView.as_view())]

blogapp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	 url(r'^$', views.home, name='home'),

	 url(r'^(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
	 url(r'^category/(?P<category_slug>[-\w]+)/$',
        views.list_of_post_by_category,
        name='list_of_post_by_category'),
	 
	 
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from ckeditor_uploader.fields import RichTextUploadingField



class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

class Category(models.Model):
	title=models.CharField(max_length=100)
	slug=models.SlugField(max_length=100, unique=True)
	image=models.ImageField(upload_to='images/category', blank=True)
	

	class Meta:
		verbose_name= 'category'
		verbose_name_plural='categories'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blogapp:list_of_post_by_category',args=[self.slug])


# Create your models here.
class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
	title=models.CharField(max_length=250)
	slug=models.SlugField(max_length=250, unique_for_date='publish')
	image=models.ImageField(upload_to='images', blank=True)
	author=models.ForeignKey(User, related_name='blog_posts')
	body=RichTextUploadingField()
	publish=models.DateTimeField(default=timezone.now)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	category=models.ManyToManyField(Category)


	objects=models.Manager()
	published=PublishedManager()


	class Meta:
		ordering = ('-publish',)

	def recent_publication(self):
		return self.publish <= timezone.now().date()
		"""return self.publish>=timezone.now().date()-datetime.timedelta(weeks=8)"""

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blogapp:post_detail',args=[self.slug])

#Model Comment here
class Comment(models.Model):
	post=models.ForeignKey('blogapp.Post', related_name='comments')
	author=models.CharField(max_length=200)
	body=models.TextField()
	created=models.DateTimeField(default=timezone.now)
	updated=models.DateTimeField(auto_now=True)
	approved_comment=models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.author, self.post)

	

	

blogapp/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=('author','body')

blogapp/api/views.py
from rest_framework.generics import ListAPIView
from blogapp.api.serializers import PostSerializer
from blogapp.models import Post


class PostListAPIView(ListAPIView):
	""" List of Blogs """
	queryset =Post.objects.all()
	serializer_class=PostSerializer

blogapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blogapp.models import Post, Category,Comment
from .forms import CommentForm

# Create your views here.
def home(request):
	posts=Post.published.all()
	allCategory=Category.objects.all()
	
	# Show 3 posts per page
	paginator=Paginator(posts,3)
	page=request.GET.get('page')
	try:
		allPost = paginator.page(page)
	except PageNotAnInteger:
		#If page is not an integer, deliver first page
		allPost=paginator.page(1)
	except EmptyPage:
		#If page is out of range, deliver last page of results
		allPost=paginator.page(paginator.num_pages)

	return render(request, 'blogapp/home.html', {'posts':allPost, 'page': page, 'categorys':allCategory})

def post_detail(request,post):
	allCategory=Category.objects.all()
	#similarPost=get_object_or_404(Post, slug=category_slug, status='published')
	post= get_object_or_404(Post, slug=post,
								  status='published')

	#List of active comments for this post
	comments=post.comments.filter(approved_comment=True)
	if request.method == 'POST' :
		# A comment wast posted
		comment_form= CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment=comment_form.save(commit=False)
			#Assign the current post to the comment
			new_comment.post=post
			#Save the comment to the database
			new_comment.save()
	else:
		comment_form=CommentForm()

	return render(request, 'blogapp/detail.html', {'post': post, 'categorys':allCategory, 'comments':comments, 'comment_form':comment_form})


def list_of_post_by_category(request, category_slug):
	categories= Category.objects.all()
	post=Post.objects.filter(status='published')
	if category_slug:
		category=get_object_or_404(Category, slug=category_slug)
		post=post.filter(category=category)
	paginator=Paginator(post,3)
	page=request.GET.get('page')
	try:
		post = paginator.page(page)
	except PageNotAnInteger:
		#If page is not an integer, deliver first page
		post=paginator.page(1)
	except EmptyPage:
		#If page is out of range, deliver last page of results
		post=paginator.page(paginator.num_pages)
	return render(request, 'category/list_of_post_by_category.html', { 'post':post,'category':category, 'categories':categories})


	

blogapp/templates/blogapp/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../../../favicon.ico"> -->

    <title> {% block title %} Bhavani's Blog {% endblock %} </title>

    <!-- blog css -->
    <link href="{% static "blogapp/css/blog.css" %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static "blogapp/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "blogapp/css/carousel.css" %}" rel="stylesheet">
  </head>

	<body>
	
	
	    {% block content %}

	    {% endblock %}
		
		
    


	    <!-- Bootstrap core JavaScript
	    ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster -->
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
	    <script src="{% static 'blogapp/js/popper.min.js' %}"></script>
	    <script src="{% static 'blogapp/js/bootstrap.min.js' %}"></script> 
	    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
	    <script src="{% static 'blogapp/js/holder.min.js' %}"></script>
	    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	    <script src="{% static 'blogapp/js/ie10-viewport-bug-workaround.js' %}"></script>
	    <script src="{% static 'blogapp/jquery/blog.js' %}"> </script>

	</body>
	<footer>
    
    		<p>&copy; 2017 Bhavani's Blog,  &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
 		 </footer>

    
</html>

blogapp/templates/blogapp/detail.html
{% extends "blogapp/base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
{% include 'blogapp/header.html' with allCategory=categorys  %}
 
 	<!--<h1> {{ post.title }} </h1>
 	<img src="{{post.image.url }}"  width="250">
 	<p class="date"> Published {{ post.publish }} by {{ post.author }}
 	{% autoescape off %}
		{{ post.body| linebreaks }}
	{% endautoescape %} -->


	<!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">{{ post.title }}</h1>

          <!-- Author -->
          <p class="lead">
            by
            {{ post.author }}
           
          </p>

          <hr>

          <!-- Date/Time -->
         
          <p class="date"> Published {{ post.publish }}
          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="{{post.image.url }}" alt="">

          <hr>

          <!-- Post Content -->
          <p class="lead">
          {% autoescape off %}
          	{{ post.body }}
          {% endautoescape %} 
          </p>

          <hr>

          <h4> {{ comments.count }} Comments </h4>
         {% for comment in comments %}
         	<div class="comment">
            <strong>{{ comment.author }} </strong>
         		<div class="date">{{ comment.created}} </div>
         		
         		<p> {{ comment.body | linebreaks }} </p>
         	</div>
         {% empty %}
         	<p> No comments here yet </p>
         {% endfor %}

         {% if new_comment %}
        <h2>Your comment has been added.</h2>
        {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Post comment"></p>
        </form>
        {%  endif %}
          <!-- Comments Form -->
          

          <!-- Single Comment -->
          

          <!-- Comment with nested comments -->
         

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                  {% for category in categorys %}
                    <li>
                      <a href="{{ category.get_absolute_url }}"> {{ category.title}}</a>
                    </li>
                   {% endfor %}
                    
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Similar Posts</h5>
            {% for post in similarPost %}
            <div class="card-body">
            <p> {{post.title}}
              
            </div>
           
           {% endfor %}
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
 
 {% endblock %}

blogapp/templates/blogapp/header.html
{% load staticfiles %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	      <a class="navbar-brand" href="{% url 'blogapp:home' %}">Bhavani's blog</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarCollapse">
	        <ul class="navbar-nav mr-auto">
	            
	          {% for category in allCategory %}
	          	
	          <li class="nav-item">
	            <a class="nav-link" href="{{category.get_absolute_url}}"> {{category}}</a>
	          </li>
	         {% endfor %}
	        </ul>
	        <form class="form-inline mt-2 mt-md-0">
	          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
	          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	        </form>
	      </div>
    </nav> 

blogapp/templates/blogapp/home.html
{% extends  'blogapp/base.html' %}

{% block title %} {{ post.title }} {% endblock %}
<body>
  {% block content %}

  {% include 'blogapp/header.html' with allCategory=categorys  %}
   
    
      <!--Carousel -->
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
       
        <div class="carousel-inner">
          {% for category in categorys %}
            <div class="carousel-item {% if forloop.first %} active {% endif %}">

                
                  
                

              <img class="first-slide" src="{{category.image.url }}" alt="First slide"> 
              <div class="container">
                <div class="carousel-caption d-none d-md-block text-left">
                  <h1>{{ category.title }}</h1> 
                </div>
              </div>          
          </div>
          {% endfor %}       
        </div>

        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


     <!-- Page Content -->
      <div class="container">
      

     

        <!-- Page Heading -->
        <h1 class="my-4">Recent Post</h1>
        <div class ="row">

        <!-- Project One -->
        {% for post in posts %}
          <div class="row">
            <div class="col-md-6">
              <a href="#">
                <img class="img-fluid rounded mb-3 mb-md-0" src="{{ post.image.url }}" alt="">
              </a>
            </div>
            
            <div class="col-md-5">
              <h3>{{ post.title }}</h3>
              <div >
                <p class="date">Published {{ post.publish }} by {{ post.author }} </p>
              </div>
              {% autoescape off %}
                <p class="card-text">{{ post.body| truncatewords:30 }} </p>
              {% endautoescape %}
              <br>
            
              
               <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
          </div>
           <hr>
      {% endfor %}
      </div>
      

     
      
     
    
     
      </div>
      <hr>

    {% include "pagination.html" with page=posts %}

    <hr>
  {% endblock %}
 
  </body>
</html>

blogapp/templates/blogapp/list.html
{% extends "blogapp/base.html" %}

{% block title %} My Blog {% endblock %}

{% block content %}
	<h1>My Blog </h1>

	{% for post in posts %}
	<h2><a href="{{ post.get_absolute_url }}">{{ post.title }} </a></h2>
	<img src="{{ post.image.url}}" width="250"> </br>
	{% autoescape off %}
		{{ post.body| truncatewords:10 }}
	{% endautoescape %}
	<p class="date">Published {{ post.publish }} by {{ post.author }} </p>
	{% endfor %}

	{% include "pagination.html" with page=posts %}

{% endblock %}

blogapp/templates/category/list_of_post_by_category.html
{% extends  'blogapp/base.html' %}
{% block title %} {{category}} {% endblock %}

{% block content %}
{% include 'blogapp/header.html' with allCategory=categories %}
<div class="headerimage">
	<img src="{{category.image.url }}" class="img-fluid" alt="Responsive image">
</div>
	

<hr>
{% for singlepost in post %}
          <div class="row">
          <div class="col-md-1"></div>

            <div class="col-md-5">
              <a href="#">
                <img class="img-fluid rounded mb-3 mb-md-0" src="{{ singlepost.image.url }}" alt="">
              </a>
            </div>
            
            <div class="col-md-5">
              <h3>{{ singlepost.title }} </h3>
              <div >
                <p class="date">Published {{ singlepost.publish }} by {{singlepost.author }} </p>
              </div>
              {% autoescape off %}
                <p class="card-text">{{ singlepost.body| truncatewords:30 }} </p>
              {% endautoescape %}
              <br>
              
               <a href="{{  singlepost.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="col-md-1"></div>
          </div>
           <hr>
      {% endfor %}

      {% include "pagination.html" with page=post %}
      <hr>
     {% endblock %}

blogapp/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div> 


          